# Generated by Django 4.1.5 on 2023-02-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aviso_api.order'),
        ),
    ]
