# Generated by Django 4.1.2 on 2023-02-22 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aviso_api', '0003_order_creator_order_worker_delete_userorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='default.png', null=True, upload_to='', verbose_name='Фотография новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='default.png', null=True, upload_to='', verbose_name='Фотография новости'),
        ),
        migrations.AddField(
            model_name='order',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография новости'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='worker',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar_default.png', null=True, upload_to='', verbose_name='Фотография новости')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ManyToManyField(null=True, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='Рабочий'),
        ),
    ]
