# Generated by Django 4.1.2 on 2023-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0006_remove_order_worker_profile_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Фотография статьи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Фотография заказа'),
        ),
    ]
