# Generated by Django 4.1.2 on 2023-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0007_alter_articles_img_alter_order_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
