# Generated by Django 4.1.2 on 2023-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0010_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Пусто', max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
