# Generated by Django 4.1.2 on 2023-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0011_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Пусто', max_length=1000, verbose_name='Описание'),
        ),
    ]
