# Generated by Django 4.1.2 on 2023-03-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='aviso_api.order', verbose_name='Заказы'),
        ),
    ]
