# Generated by Django 4.1.2 on 2023-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0016_alter_profile_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preview',
            field=models.CharField(default=models.CharField(max_length=150, verbose_name='Название заказа'), max_length=150, verbose_name='Превью'),
        ),
    ]
