# Generated by Django 4.1.2 on 2023-03-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0017_order_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='preview',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Превью'),
        ),
    ]
