# Generated by Django 4.1.2 on 2023-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviso_api', '0018_alter_order_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='article/', verbose_name='Фотография статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='news/', verbose_name='Фотография новости'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='orders/', verbose_name='Фотография заказа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar_default.jpg', null=True, upload_to='profile/', verbose_name='Фотография профиля'),
        ),
    ]
